repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
        language_version: python3.10
